[variables]
CMAKE_C_STANDARD = "90"

[target.zlib]
type = "library"
include-directories = ["."]
compile-definitions = ["_LIB"]
sources = ["*.c", "*.h"]
# unix.compile-options = ["-std=c90"]
cmake-before = "project(zlib C)"
