[target.libjxr]
type = "library"
compile-features = ["c_std_99"]
include-directories = [".", "image/sys/", "jxrgluelib/", "common/include/"]
compile-definitions = ["_LIB", "DISABLE_PERF_MEASUREMENT"]
unix.compile-definitions = ["__ANSI__"]
sources = ["**.c"]
